let currentLang='en',currentPart=1,trackIndex=-1,reading=false;
const PART1_TITLES={en:'Left Behind',fr:'Abandonné',es:'Abandonado'};
const PART1_PRACTICE={en:{repeat:['I’ve sprained my ankle.','Bill did not look around.','The man was left alone.'],speak:'Retell Part 1 briefly in 3–4 sentences.',model:'Two exhausted men are crossing the wilderness. One of them injures his ankle in the icy water. He calls Bill for help, but Bill keeps walking and does not look back. The injured man is left alone.',reflection:'Why is Bill’s departure the turning point of the scene? Answer in 1–2 sentences in your own words.'},fr:{repeat:['Je me suis blessé à la cheville.','Bill ne se retourna pas.','L’homme blessé resta seul.'],speak:'Racontez brièvement la Partie 1 en 3–4 phrases.',model:'Deux hommes épuisés traversent une région sauvage. L’un d’eux se blesse à la cheville dans l’eau glacée. Il appelle Bill à l’aide, mais Bill continue son chemin sans se retourner. L’homme blessé reste seul.',reflection:'Pourquoi le départ de Bill est-il le tournant de la scène ? Répondez en 1–2 phrases avec vos propres mots.'},es:{repeat:['Me he torcido el tobillo.','Bill no se dio la vuelta.','El hombre herido se quedó solo.'],speak:'Cuenta brevemente la Parte 1 en 3–4 frases.',model:'Dos hombres agotados atraviesan una región salvaje. Uno de ellos se lesiona el tobillo en el agua helada. Pide ayuda a Bill, pero Bill sigue caminando sin darse la vuelta. El hombre herido se queda solo.',reflection:'¿Por qué la marcha de Bill es el punto de inflexión de la escena? Responde en 1–2 frases con tus propias palabras.'}};
function labels(lang){return lang==='fr'?{part:'Partie',read:'Lire',vocab:'Vocabulaire',q:'Compréhension',answer:'Voir la réponse',audio:'Lecture littéraire',showRu:'🇷🇺 Afficher la traduction russe',model:'Réponse modèle',prev:'← Partie précédente',next:'Partie suivante →',pending:'🎧 Lecture littéraire de cette partie : en préparation.'}:lang==='es'?{part:'Parte',read:'Leer',vocab:'Vocabulario',q:'Comprensión',answer:'Ver respuesta',audio:'Lectura literaria',showRu:'🇷🇺 Mostrar traducción rusa',model:'Respuesta modelo',prev:'← Parte anterior',next:'Parte siguiente →',pending:'🎧 Lectura literaria de esta parte: en preparación.'}:{part:'Part',read:'Read',vocab:'Vocabulary',q:'Comprehension',answer:'Show answer',audio:'Literary reading',showRu:'🇷🇺 Show Russian translation',model:'Model answer',prev:'← Previous Part',next:'Next Part →',pending:'🎧 Literary reading for this Part is in preparation.'};}
function getData(){if(currentPart===1){const d=KAROLIN[currentLang];return{title:PART1_TITLES[currentLang],level:'B1–B2',text:d.text,ru:[...(window.KAROLIN_RU1||[]),...(window.KAROLIN_RU2||[])],words:d.words,qs:d.qs,practice:PART1_PRACTICE[currentLang],audio:d.audio||[]};}const p=window.KAROLIN_PARTS_2_10[String(currentPart)];return{title:p.title[currentLang],level:p.level,text:p.text[currentLang],ru:p.ru,words:p.vocab[currentLang],qs:p.questions[currentLang],practice:p.practice[currentLang],audio:p.audio[currentLang]||[]};}
function render(){stopReading();const l=labels(currentLang),d=getData();document.getElementById('breadcrumb').textContent=`Bibliothèque → Jack London → Love of Life → ${l.part} ${currentPart}`;document.getElementById('partMeta').textContent=`${l.part} ${currentPart} / 10 · ${d.title} · ${d.level}`;document.getElementById('readLabel').textContent=l.read;document.getElementById('vocabLabel').textContent=`${l.vocab} · ${d.words.length}`;document.getElementById('questionLabel').textContent=l.q;document.getElementById('audioLabel').textContent=l.audio;document.querySelector('#ruDetails summary').textContent=l.showRu;document.getElementById('reader').innerHTML=d.text.map((s,i)=>`<p class="sentence" data-i="${i}">${s}</p>`).join('');document.getElementById('ruText').innerHTML=d.ru.map(x=>`<p>${x}</p>`).join('');document.getElementById('vocabGrid').innerHTML=d.words.map(([w,m,e])=>`<div class="v"><button class="sound" type="button" aria-label="Pronounce ${w}" onclick='speakVocab(${JSON.stringify(w)})'>🔊</button><div class="vtxt"><b>${w}</b><span>${m}</span><em>${e}</em></div></div>`).join('');document.getElementById('questions').innerHTML=d.qs.map(([q,a])=>`<div class="q"><b>${q}</b><details><summary>${l.answer}</summary><div>${a}</div></details></div>`).join('');const p=d.practice;document.getElementById('practiceBlock').innerHTML=`<p><b>Repeat</b></p><ul>${p.repeat.map(x=>`<li>${x}</li>`).join('')}</ul><p><b>Speak</b><br>${p.speak}</p><details><summary>${l.model}</summary><p>${p.model}</p></details><p><b>Reflection</b><br>${p.reflection}</p>`;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.lang===currentLang));document.querySelectorAll('.part').forEach(b=>{const n=Number(b.dataset.part);b.classList.toggle('active',n===currentPart);const title=n===1?PART1_TITLES[currentLang]:window.KAROLIN_PARTS_2_10[String(n)].title[currentLang];b.textContent=`${n} · ${title}`;});document.getElementById('footerPart').textContent=`Love of Life · ${l.part} ${currentPart}/10`;document.getElementById('prevPart').textContent=l.prev;document.getElementById('nextPart').textContent=l.next;document.getElementById('prevPart').disabled=currentPart===1;document.getElementById('nextPart').disabled=currentPart===10;const play=document.getElementById('playBtn'),status=document.getElementById('audioStatus'),player=document.getElementById('audioPlayer');if(d.audio.length){play.disabled=false;play.textContent=`▶ ${l.audio} · ${l.part} ${currentPart}`;status.textContent='';player.style.display='block';}else{play.disabled=true;play.textContent=`▶ ${l.audio}`;status.textContent=l.pending;player.style.display='none';}}
function setLang(lang){currentLang=lang;render();}
function setPart(n){if(n<1||n>10)return;currentPart=n;render();window.scrollTo({top:0,behavior:'smooth'});}
function clearHighlight(){document.querySelectorAll('.sentence.on').forEach(x=>x.classList.remove('on'));}
function highlightTrack(i){clearHighlight();const list=[...document.querySelectorAll('.sentence')],audio=getData().audio,n=audio.length;if(!n)return;const a=Math.floor(i*list.length/n),b=Math.max(a+1,Math.floor((i+1)*list.length/n));list.slice(a,b).forEach(x=>x.classList.add('on'));if(list[a])list[a].scrollIntoView({behavior:'smooth',block:'center'});}
function playPart(){const audio=getData().audio;if(!audio.length)return;stopReading();reading=true;trackIndex=0;playTrack();}
function playTrack(){const audio=getData().audio;if(!reading||trackIndex>=audio.length){stopReading(false);return;}highlightTrack(trackIndex);const p=document.getElementById('audioPlayer');p.style.display='block';p.src=audio[trackIndex];p.onended=()=>{trackIndex++;playTrack();};p.play().catch(()=>{});}
function stopReading(reset=true){reading=false;trackIndex=-1;clearHighlight();const p=document.getElementById('audioPlayer');if(p){p.pause();if(reset){p.removeAttribute('src');p.load();}}if(window.speechSynthesis)window.speechSynthesis.cancel();}
function speakVocab(text){if(!window.speechSynthesis)return;window.speechSynthesis.cancel();const locale=currentLang==='fr'?'fr-FR':currentLang==='es'?'es-ES':'en-US';const u=new SpeechSynthesisUtterance(text);u.lang=locale;u.rate=.78;const voices=window.speechSynthesis.getVoices();const preferred=voices.find(v=>v.lang===locale)||voices.find(v=>v.lang&&v.lang.toLowerCase().startsWith(locale.slice(0,2)));if(preferred)u.voice=preferred;window.speechSynthesis.speak(u);}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));document.querySelectorAll('.part').forEach(b=>b.addEventListener('click',()=>setPart(Number(b.dataset.part))));document.getElementById('playBtn').addEventListener('click',playPart);document.getElementById('stopBtn').addEventListener('click',()=>stopReading());document.getElementById('prevPart').addEventListener('click',()=>setPart(currentPart-1));document.getElementById('nextPart').addEventListener('click',()=>setPart(currentPart+1));
const extraPart7Audio=document.createElement('script');extraPart7Audio.src='part-7-audio.js?v=13092026e';extraPart7Audio.onload=()=>{if(currentPart===7)render();};document.head.appendChild(extraPart7Audio);
render();